name: Deploy Backend
on:
  workflow_call:
    inputs:
      dockerfile: { type: string, default: "backend.Dockerfile" }
      context: { type: string, default: "." }
    secrets:
      DO_TOKEN:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Checkout Template Repo For Scripts
        uses: actions/checkout@v5
        with:
          repository: GenerateNU/shiperate
          ref: main
          path: ./shiperate

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install docker

      - name: Run deploy script
        run: |
          python3 shiperate/scripts/deploy.py
        env:
          DOCKERFILE: ${{ inputs.dockerfile }}
          CONTEXT: ${{ inputs.context }}
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
